version: '3'
services:
  crawler:
    build: ./crawler
    container_name: crawlerBackend
    # restart: always
    # env_file:
    #   - ./.env.FLA
    environment:
      APP_NAME: FlaskApp
      TZ: Asia/Taipei
    ports:
      - 8090:8080
    volumes:
      - ./crawler:/app
      - ./postgres/schema:/schema
    depends_on:
      - postgres
    networks:
      app_net:
        ipv4_address: 172.128.0.4

  postgres:
    build: ./postgres
    restart: always
    container_name: postgres_crawler
    env_file:
      - .env.sql
    volumes:
      # - ./db-data:/var/lib/postgresql/data
      # - db-data:/var/lib/postgresql/data
      - db-data2:/var/lib/postgresql/data
      # - ./postgres/template.conf:/var/lib/postgresql/data/postgresql.conf
    expose:
      - 5432
    networks:
      app_net:
        ipv4_address: 172.128.0.2

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    env_file:
      - .env.pgadmin
    ports:
      - "8082:80"
    volumes:
      # - pgadmin-data:/var/lib/postgresql/data
      - ./pgadmin-data:/var/lib/pgadmin
    links:
      - "postgres:pgsql-server"
    networks:
      app_net:
        ipv4_address: 172.128.0.3


volumes:
    db-data2:
    # pgadmin-data:

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.128.0.0/16
          gateway: 172.128.0.1