version: '3'
services:
  crawler:
    build: ./crawler
    container_name: crawlerBackend
    # restart: always
    # env_file:
    #   - ./.env.FLA
    environment:
      APP_NAME: FlaskApp
      TZ: 
    ports:
      - 8080:8080
    volumes:
      - ./crawler:/app
      - ./postgres/schema:/schema
    depends_on:
      - postgres
    networks:
      app_net:
        ipv4_address: 172.128.0.4

  postgres:
    build: ./postgres
    restart: always
    container_name: postgres_crawler
    environment:
      TZ: 
      POSTGRES_DB: 
      POSTGRES_USER: 
      POSTGRES_PASSWORD: 
    # env_file:
    #   - ./.env.DB
    volumes:
      # - ./db-data:/var/lib/postgresql/data
      - db-data:/var/lib/postgresql/data
      # - ./postgres/template.conf:/var/lib/postgresql/data/postgresql.conf
    # expose:
    #   - 5432
    ports:
      - "5432:5432"
    networks:
      app_net:
        ipv4_address: 172.128.0.2

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      TZ: 
      PGADMIN_DEFAULT_EMAIL: 
      PGADMIN_DEFAULT_PASSWORD: 
      PGADMIN_LISTEN_PORT: 
    ports:
      - "8081:80"
    volumes:
      - pgadmin-data:/var/lib/postgresql/data
    #   - ./pgadmin-data:/var/lib/pgadmin
    links:
      - "postgres:pgsql-server"
    networks:
      app_net:
        ipv4_address: 172.128.0.3


volumes:
    db-data:
    pgadmin-data:


networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.128.0.0/16
          gateway: 172.128.0.1